import Link from "next/link";

export default function TermsPage() {
  return (
    <div className="min-h-screen flex flex-col items-center justify-center bg-gray-50 p-6">
      <div className="bg-white p-8 rounded-lg shadow-md w-full max-w-3xl text-left">
        <h1 className="text-3xl font-bold text-gray-900 mb-6">📜 Terms and Conditions</h1>

        <p className="text-gray-700 mb-4">
          Last updated: <strong>March 2025</strong>
        </p>

        <h2 className="text-xl font-semibold text-gray-800 mt-6">1. Introduction</h2>
        <p className="text-gray-700">
          Welcome to **AImealPrep** ("we", "our", "us"). These Terms and Conditions govern your use of our website and services. 
          By accessing or using our platform, you agree to these Terms in full.
        </p>

        <h2 className="text-xl font-semibold text-gray-800 mt-6">2. User Eligibility</h2>
        <p className="text-gray-700">
          You must be at least **18 years old** to use this website. By using our services, you confirm that you meet this requirement.
        </p>

        <h2 className="text-xl font-semibold text-gray-800 mt-6">3. Services Provided</h2>
        <p className="text-gray-700">
          AImealPrep provides personalized meal plans based on user inputs. Our services do **not** constitute medical or 
          nutritional advice. Please consult a professional before making dietary changes.
        </p>

        <h2 className="text-xl font-semibold text-gray-800 mt-6">4. Account and Payment</h2>
        <ul className="list-disc pl-5 text-gray-700">
          <li>You agree to provide accurate information when signing up.</li>
          <li>All payments are **one-time fees**, as clearly stated before checkout.</li>
          <li>We process payments securely via **Stripe**, and we do not store payment details.</li>
        </ul>

        <h2 className="text-xl font-semibold text-gray-800 mt-6">5. Refund Policy</h2>
        <p className="text-gray-700">
          We offer **refunds only in specific cases**, such as technical issues that prevent meal plan delivery.
          Refund requests must be made within **7 days** of purchase. Read our 
          <Link href="/refund-policy" className="text-blue-600 hover:underline"> Refund Policy</Link>.
        </p>

        <h2 className="text-xl font-semibold text-gray-800 mt-6">6. Data Protection (GDPR Compliance)</h2>
        <p className="text-gray-700">
          We respect your privacy and comply with the **General Data Protection Regulation (GDPR)**. 
          - Your personal data is stored securely in **Supabase** and is not shared with third parties.
          - You can request data deletion at any time via <a href="mailto:support@ai-mealprep.com" className="text-blue-600 hover:underline">support@ai-mealprep.com</a>.
        </p>

        <h2 className="text-xl font-semibold text-gray-800 mt-6">7. Acceptable Use</h2>
        <ul className="list-disc pl-5 text-gray-700">
          <li>You must not misuse our platform, including hacking or attempting to extract unauthorized data.</li>
          <li>Content generated by our AI is for personal use only and may not be resold.</li>
        </ul>

        <h2 className="text-xl font-semibold text-gray-800 mt-6">8. Liability & Disclaimer</h2>
        <p className="text-gray-700">
          AImealPrep is provided "as is". We do not guarantee that meal plans will suit every individual’s dietary needs. 
          We are not responsible for any health outcomes resulting from meal plans.
        </p>

        <h2 className="text-xl font-semibold text-gray-800 mt-6">9. Changes to Terms</h2>
        <p className="text-gray-700">
          We may update these Terms from time to time. The latest version will always be available on this page.
        </p>

        <h2 className="text-xl font-semibold text-gray-800 mt-6">10. Contact Us</h2>
        <p className="text-gray-700">
          If you have any questions about these Terms, you can contact us at 
          <a href="mailto:support@ai-mealprep.com" className="text-blue-600 hover:underline"> support@ai-mealprep.com</a>.
        </p>

        {/* Back to Home Button */}
        <div className="text-center mt-6">
          <Link href="/" className="bg-blue-600 text-white py-2 px-4 rounded-md hover:bg-blue-700">
            Back to Home
          </Link>
        </div>
      </div>
    </div>
  );
}
